version: "3"
services:
  server:
    build: .
    container_name: docker_web_app_server
    env_file:
      - .env
    ports:
      - 5000:8080
    volumes:
      - ./:/home/app
    depends_on:
      - db
    command: sh -c "dockerize -wait tcp://db:3306 -timeout 300s -wait-retry-interval 5s npm run dev"
  db:
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_DATABASE: 'docker_web'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    volumes:
      - ./config/data/mysql:/var/lib/mysql
      - ./config/data/setup.sql:/docker-entrypoint-initdb.d/setup.sql
